# config/project_configuration.yml

# Paths for raw data
data:
  train_path: "data/raw/train.csv"
  test_path: "data/raw/test.csv"
  new_data_path: "data/raw/new_data.csv"  # Optional, for inference on new unseen data

# Paths for processed data
processed_data:
  train: "data/processed/train_processed.pkl"
  test: "data/processed/test_processed.pkl"

# Paths for models
models:
  har_model: "models/har_model.pkl"
  scaler: "models/scaler.pkl"
  pca: "models/pca.pkl"
  encoder: "models/encoder.pkl"
  training_features: "models/training_features.pkl"
  n_estimators: 280
  max_depth: 15
  min_samples_split: 5
  random_state: 42
  early_stopping_rounds: 10,
  class_weight: None

# Paths for results
results:
  accuracy: "results/accuracy.txt"
  classification_report: "results/classification_report.txt"
  confusion_matrix: "results/confusion_matrix.png"
  feature_distributions: "results/feature_distributions/"

# Model hyperparameters
model:
  n_estimators: 280
  max_depth: 15
  min_samples_split: 5
  random_state: 42
  class_weight: "balanced"

# Preprocessing parameters
preprocessing:
  correlation_threshold: 0.97
  vif_threshold: 10
  pca_variance: 0.95

# Logging configuration
logging:
  log_file: "logs/app.log"
  log_level: "INFO"

# config/config.yaml

# EDA parameters
eda:
  class_distribution_figsize: [8, 6]  # Figure size for class distribution plot
  correlation_matrix_figsize: [12, 8]  # Figure size for correlation matrix plot
  histogram_figsize: [20, 15]  # Figure size for histogram plots
  boxplot_figsize: [20, 8]  # Figure size for boxplot plots
  features_per_plot: 100  # Number of features per histogram plot
  boxplot_features: 100  # Number of features per boxplot plot

algorithms:
  - RandomForest
  - SVM
  - XGBoost
  - CNN
  - LSTM